coverage:
  range: 70..100
  round: down
  precision: 2

comment:
  layout: "reach, diff, flags, files, footer"

ignore:
  - "src/main/java/com/github/mikesafonov/prometheus/telegram/config/*"
  - "src/main/resources/*"
